# Weblate에서 가져온 언어별 복수형 규칙
# 자동 생성됨 - get_weblate_languages.py

PLURAL_RULES = {
    'aa': 'nplurals=2; plural=(n != 1)',
    'ab': 'nplurals=2; plural=(n != 1)',
    'abr': 'nplurals=2; plural=(n != 1)',
    'ace': 'nplurals=1; plural=0',
    'ach': 'nplurals=2; plural=(n > 1)',
    'ada': 'nplurals=2; plural=(n != 1)',
    'ady': 'nplurals=2; plural=(n > 1)',
    'ae': 'nplurals=2; plural=(n != 1)',
    'aeb': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'af': 'nplurals=2; plural=(n != 1)',
    'afh': 'nplurals=2; plural=(n != 1)',
    'aii': 'nplurals=2; plural=(n != 1)',
    'ain': 'nplurals=2; plural=(n != 1)',
    'ak': 'nplurals=2; plural=(n > 1)',
    'akk': 'nplurals=2; plural=(n != 1)',
    'ale': 'nplurals=2; plural=(n != 1)',
    'aln': 'nplurals=2; plural=(n != 1)',
    'alt': 'nplurals=2; plural=(n != 1)',
    'am': 'nplurals=2; plural=(n > 1)',
    'ami': 'nplurals=2; plural=(n != 1)',
    'an': 'nplurals=2; plural=(n != 1)',
    'ang': 'nplurals=2; plural=(n != 1)',
    'anp': 'nplurals=2; plural=(n != 1)',
    'apc': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'apd': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_BH': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_DZ': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_EG': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_KW': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_LY': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_MA': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_SA': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_XB': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'ar_YE': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5',
    'arc': 'nplurals=2; plural=(n != 1)',
    'arn': 'nplurals=2; plural=(n > 1)',
    'arp': 'nplurals=2; plural=(n != 1)',
    'arq': 'nplurals=6; plural=(n == 0) ? 0 : ((n == 1) ? 1 : ((n == 2) ? 2 : ((n % 100 >= 3 && n % 100 <= 10) ? 3 : ((n % 100 >= 11 && n % 100 <= 99) ? 4 : 5))))',
    'ars': 'nplurals=6; plural=(n == 0) ? 0 : ((n == 1) ? 1 : ((n == 2) ? 2 : ((n % 100 >= 3 && n % 100 <= 10) ? 3 : ((n % 100 >= 11 && n % 100 <= 99) ? 4 : 5))))',
    'arw': 'nplurals=2; plural=(n != 1)',
    'arz': 'nplurals=6; plural=(n == 0) ? 0 : ((n == 1) ? 1 : ((n == 2) ? 2 : ((n % 100 >= 3 && n % 100 <= 10) ? 3 : ((n % 100 >= 11 && n % 100 <= 99) ? 4 : 5))))',
    'as': 'nplurals=2; plural=(n > 1)',
    'asa': 'nplurals=2; plural=(n != 1)',
    'ast': 'nplurals=2; plural=(n != 1)',
    'av': 'nplurals=2; plural=(n != 1)',
    'avk': 'nplurals=2; plural=(n != 1)',
    'awa': 'nplurals=2; plural=(n != 1)',
    'ay': 'nplurals=1; plural=0',
    'ayc': 'nplurals=2; plural=(n != 1)',
    'az': 'nplurals=2; plural=(n != 1)',
    'azb': 'nplurals=2; plural=(n != 1)',
    'ba': 'nplurals=2; plural=(n != 1)',
    'bal': 'nplurals=2; plural=(n != 1)',
    'ban': 'nplurals=2; plural=(n != 1)',
    'bar': 'nplurals=2; plural=(n != 1)',
    'bas': 'nplurals=2; plural=(n != 1)',
    'bbc': 'nplurals=2; plural=(n != 1)',
    'bci': 'nplurals=2; plural=(n != 1)',
    'be': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'be_Latn': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'bej': 'nplurals=2; plural=(n != 1)',
    'bem': 'nplurals=2; plural=(n != 1)',
    'ber': 'nplurals=2; plural=(n != 1)',
    'bew': 'nplurals=2; plural=(n != 1)',
    'bez': 'nplurals=2; plural=(n != 1)',
    'bg': 'nplurals=2; plural=(n != 1)',
    'bgc': 'nplurals=2; plural=(n != 1)',
    'bgn': 'nplurals=2; plural=(n != 1)',
    'bh': 'nplurals=2; plural=(n > 1)',
    'bhb': 'nplurals=2; plural=(n != 1)',
    'bhi': 'nplurals=2; plural=(n != 1)',
    'bho': 'nplurals=2; plural=(n > 1)',
    'bi': 'nplurals=2; plural=(n != 1)',
    'bik': 'nplurals=2; plural=(n != 1)',
    'bin': 'nplurals=2; plural=(n != 1)',
    'bjj': 'nplurals=2; plural=(n != 1)',
    'bjn': 'nplurals=2; plural=(n != 1)',
    'bla': 'nplurals=2; plural=(n != 1)',
    'blo': 'nplurals=3; plural=(n == 0) ? 0 : ((n == 1) ? 1 : 2)',
    'bm': 'nplurals=1; plural=0',
    'bn': 'nplurals=2; plural=(n > 1)',
    'bn_BD': 'nplurals=2; plural=(n > 1)',
    'bn_IN': 'nplurals=2; plural=(n > 1)',
    'bnt': 'nplurals=2; plural=(n != 1)',
    'bo': 'nplurals=1; plural=0',
    'bo_CN': 'nplurals=1; plural=0',
    'bqi': 'nplurals=2; plural=(n != 1)',
    'br': 'nplurals=5; plural=(n % 10 == 1 && n % 100 != 11 && n % 100 != 71 && n % 100 != 91) ? 0 : ((n % 10 == 2 && n % 100 != 12 && n % 100 != 72 && n % 100 != 92) ? 1 : ((((n % 10 == 3 || n % 10 == 4) || n % 10 == 9) && (n % 100 < 10 || n % 100 > 19) && (n % 100 < 70 || n % 100 > 79) && (n % 100 < 90 || n % 100 > 99)) ? 2 : ((n != 0 && n % 1000000 == 0) ? 3 : 4)))',
    'bra': 'nplurals=2; plural=(n != 1)',
    'brb': 'nplurals=2; plural=(n != 1)',
    'brh': 'nplurals=2; plural=(n != 1)',
    'brx': 'nplurals=2; plural=(n != 1)',
    'bs': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'bs_Cyrl': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'bs_Latn': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'bua': 'nplurals=2; plural=(n != 1)',
    'bug': 'nplurals=2; plural=(n != 1)',
    'bum': 'nplurals=2; plural=(n != 1)',
    'byn': 'nplurals=2; plural=(n != 1)',
    'ca': 'nplurals=2; plural=(n != 1)',
    'ca@valencia': 'nplurals=2; plural=(n != 1)',
    'ca_AD': 'nplurals=2; plural=(n != 1)',
    'cad': 'nplurals=2; plural=(n != 1)',
    'cak': 'nplurals=2; plural=(n != 1)',
    'car': 'nplurals=2; plural=(n != 1)',
    'cdo_Hans': 'nplurals=1; plural=0',
    'cdo_Hant': 'nplurals=1; plural=0',
    'cdo_Latn': 'nplurals=1; plural=0',
    'ce': 'nplurals=2; plural=(n != 1)',
    'ceb': 'nplurals=2; plural=n != 1 && n != 2 && n != 3 && (n % 10 == 4 || n % 10 == 6 || n % 10 == 9)',
    'cgg': 'nplurals=2; plural=(n != 1)',
    'ch': 'nplurals=2; plural=(n != 1)',
    'chb': 'nplurals=2; plural=(n != 1)',
    'chg': 'nplurals=2; plural=(n != 1)',
    'chk': 'nplurals=2; plural=(n != 1)',
    'chm': 'nplurals=2; plural=(n != 1)',
    'chn': 'nplurals=2; plural=(n != 1)',
    'cho': 'nplurals=2; plural=(n != 1)',
    'chp': 'nplurals=2; plural=(n != 1)',
    'chr': 'nplurals=2; plural=(n != 1)',
    'chy': 'nplurals=2; plural=(n != 1)',
    'ckb': 'nplurals=2; plural=(n != 1)',
    'ckb_IQ': 'nplurals=2; plural=(n != 1)',
    'ckb_IR': 'nplurals=2; plural=(n != 1)',
    'cnr': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'cnr_Cyrl': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'co': 'nplurals=2; plural=(n != 1)',
    'cop': 'nplurals=2; plural=(n != 1)',
    'cpe': 'nplurals=2; plural=(n != 1)',
    'cpf': 'nplurals=2; plural=(n != 1)',
    'cpp': 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2',
    'cpx_Hans': 'nplurals=1; plural=0',
    'cpx_Hant': 'nplurals=1; plural=0',
    'cpx_Latn': 'nplurals=1; plural=0',
    'cr': 'nplurals=2; plural=(n != 1)',
    'crh': 'nplurals=1; plural=0',
    'crp': 'nplurals=2; plural=(n != 1)',
    'cs': 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2',
    'csb': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'csw': 'nplurals=2; plural=(n > 1)',
    'cu': 'nplurals=2; plural=(n != 1)',
    'cv': 'nplurals=2; plural=(n != 1)',
    'cy': 'nplurals=6; plural=(n==0) ? 0 : (n==1) ? 1 : (n==2) ? 2 : (n==3) ? 3 :(n==6) ? 4 : 5',
    'da': 'nplurals=2; plural=(n != 1)',
    'dak': 'nplurals=2; plural=(n != 1)',
    'dar': 'nplurals=2; plural=(n != 1)',
    'dcc': 'nplurals=2; plural=(n != 1)',
    'de': 'nplurals=2; plural=(n != 1)',
    'de@formal': 'nplurals=2; plural=(n != 1)',
    'de@informal': 'nplurals=2; plural=(n != 1)',
    'de_1901': 'nplurals=2; plural=(n != 1)',
    'de_AT': 'nplurals=2; plural=(n != 1)',
    'de_CH': 'nplurals=2; plural=(n != 1)',
    'de_LU': 'nplurals=2; plural=(n != 1)',
    'del': 'nplurals=2; plural=(n != 1)',
    'den': 'nplurals=2; plural=(n != 1)',
    'dgr': 'nplurals=2; plural=(n != 1)',
    'din': 'nplurals=2; plural=(n != 1)',
    'dje': 'nplurals=2; plural=(n != 1)',
    'dnj': 'nplurals=2; plural=(n != 1)',
    'dnk': 'nplurals=2; plural=(n != 1)',
    'doi': 'nplurals=2; plural=(n > 1)',
    'dru': 'nplurals=2; plural=(n != 1)',
    'dry': 'nplurals=2; plural=(n != 1)',
    'dsb': 'nplurals=4; plural=(n % 100 == 1) ? 0 : ((n % 100 == 2) ? 1 : ((n % 100 == 3 || n % 100 == 4) ? 2 : 3))',
    'dua': 'nplurals=2; plural=(n != 1)',
    'dum': 'nplurals=2; plural=(n != 1)',
    'dv': 'nplurals=2; plural=(n != 1)',
    'dyu': 'nplurals=2; plural=(n != 1)',
    'dz': 'nplurals=1; plural=0',
    'ee': 'nplurals=2; plural=(n != 1)',
    'efi': 'nplurals=2; plural=(n != 1)',
    'egl': 'nplurals=2; plural=(n != 1)',
    'egy': 'nplurals=2; plural=(n != 1)',
    'eka': 'nplurals=2; plural=(n != 1)',
    'el': 'nplurals=2; plural=(n != 1)',
    'elx': 'nplurals=2; plural=(n != 1)',
    'en': 'nplurals=2; plural=(n != 1)',
    'en@pirate': 'nplurals=2; plural=(n != 1)',
    'en_AU': 'nplurals=2; plural=(n != 1)',
    'en_CA': 'nplurals=2; plural=(n != 1)',
    'en_GB': 'nplurals=2; plural=(n != 1)',
    'en_IE': 'nplurals=2; plural=(n != 1)',
    'en_IN': 'nplurals=2; plural=(n != 1)',
    'en_NZ': 'nplurals=2; plural=(n != 1)',
    'en_PH': 'nplurals=2; plural=(n != 1)',
    'en_Shaw': 'nplurals=2; plural=(n != 1)',
    'en_Shaw_GB': 'nplurals=2; plural=(n != 1)',
    'en_Shaw_US': 'nplurals=2; plural=(n != 1)',
    'en_US': 'nplurals=2; plural=(n != 1)',
    'en_XA': 'nplurals=2; plural=(n != 1)',
    'en_ZA': 'nplurals=2; plural=(n != 1)',
    'en_devel': 'nplurals=2; plural=(n != 1)',
    'enm': 'nplurals=2; plural=(n != 1)',
    'eo': 'nplurals=2; plural=(n != 1)',
    'es': 'nplurals=2; plural=(n != 1)',
    'es@formal': 'nplurals=2; plural=(n != 1)',
    'es@informal': 'nplurals=2; plural=(n != 1)',
    'es_419': 'nplurals=2; plural=(n != 1)',
    'es_AR': 'nplurals=2; plural=(n != 1)',
    'es_BO': 'nplurals=2; plural=(n != 1)',
    'es_CL': 'nplurals=2; plural=(n != 1)',
    'es_CO': 'nplurals=2; plural=(n != 1)',
    'es_CR': 'nplurals=2; plural=(n != 1)',
    'es_CU': 'nplurals=2; plural=(n != 1)',
    'es_DO': 'nplurals=2; plural=(n != 1)',
    'es_EC': 'nplurals=2; plural=(n != 1)',
    'es_MX': 'nplurals=2; plural=(n != 1)',
    'es_NI': 'nplurals=2; plural=(n != 1)',
    'es_PA': 'nplurals=2; plural=(n != 1)',
    'es_PE': 'nplurals=2; plural=(n != 1)',
    'es_PR': 'nplurals=2; plural=(n != 1)',
    'es_SV': 'nplurals=2; plural=(n != 1)',
    'es_US': 'nplurals=2; plural=(n != 1)',
    'es_UY': 'nplurals=2; plural=(n != 1)',
    'es_VE': 'nplurals=2; plural=(n != 1)',
    'et': 'nplurals=2; plural=(n != 1)',
    'eu': 'nplurals=2; plural=(n != 1)',
    'ewo': 'nplurals=2; plural=(n != 1)',
    'ext': 'nplurals=2; plural=(n != 1)',
    'fa': 'nplurals=2; plural=(n > 1)',
    'fan': 'nplurals=2; plural=(n != 1)',
    'fat': 'nplurals=2; plural=(n != 1)',
    'fbl': 'nplurals=2; plural=(n != 1)',
    'ff': 'nplurals=2; plural=(n > 1)',
    'ffm': 'nplurals=2; plural=(n != 1)',
    'fi': 'nplurals=2; plural=(n != 1)',
    'fil': 'nplurals=2; plural=n != 1 && n != 2 && n != 3 && (n % 10 == 4 || n % 10 == 6 || n % 10 == 9)',
    'fj': 'nplurals=2; plural=(n != 1)',
    'fo': 'nplurals=2; plural=(n != 1)',
    'fon': 'nplurals=2; plural=(n != 1)',
    'fr': 'nplurals=2; plural=(n > 1)',
    'fr@formal': 'nplurals=2; plural=(n > 1)',
    'fr@informal': 'nplurals=2; plural=(n > 1)',
    'fr_AG': 'nplurals=2; plural=(n > 1)',
    'fr_BE': 'nplurals=2; plural=(n > 1)',
    'fr_CA': 'nplurals=2; plural=(n > 1)',
    'fr_CH': 'nplurals=2; plural=(n > 1)',
    'fr_LU': 'nplurals=2; plural=(n > 1)',
    'fr_SN': 'nplurals=2; plural=(n > 1)',
    'frc': 'nplurals=2; plural=(n > 1)',
    'frk': 'nplurals=2; plural=(n != 1)',
    'frm': 'nplurals=2; plural=(n != 1)',
    'fro': 'nplurals=2; plural=(n != 1)',
    'frp': 'nplurals=2; plural=(n > 1)',
    'frr': 'nplurals=2; plural=(n != 1)',
    'frs': 'nplurals=2; plural=(n != 1)',
    'fuq': 'nplurals=2; plural=(n != 1)',
    'fur': 'nplurals=2; plural=(n != 1)',
    'fuv': 'nplurals=2; plural=(n != 1)',
    'fvr': 'nplurals=2; plural=(n != 1)',
    'fy': 'nplurals=2; plural=(n != 1)',
    'ga': 'nplurals=5; plural=n==1 ? 0 : n==2 ? 1 : (n>2 && n<7) ? 2 :(n>6 && n<11) ? 3 : 4',
    'gaa': 'nplurals=2; plural=(n != 1)',
    'gan_Hans': 'nplurals=1; plural=0',
    'gan_Hant': 'nplurals=1; plural=0',
    'gay': 'nplurals=2; plural=(n != 1)',
    'gba': 'nplurals=2; plural=(n != 1)',
    'gbm': 'nplurals=2; plural=(n != 1)',
    'gd': 'nplurals=4; plural=(n==1 || n==11) ? 0 : (n==2 || n==12) ? 1 : (n > 2 && n < 20) ? 2 : 3',
    'gez': 'nplurals=2; plural=(n != 1)',
    'gil': 'nplurals=2; plural=(n != 1)',
    'gl': 'nplurals=2; plural=(n != 1)',
    'glk': 'nplurals=2; plural=(n != 1)',
    'gmh': 'nplurals=2; plural=(n != 1)',
    'gn': 'nplurals=2; plural=(n != 1)',
    'goh': 'nplurals=2; plural=(n != 1)',
    'gom': 'nplurals=2; plural=(n != 1)',
    'gon': 'nplurals=2; plural=(n != 1)',
    'gor': 'nplurals=2; plural=(n != 1)',
    'got': 'nplurals=2; plural=(n != 1)',
    'grb': 'nplurals=2; plural=(n != 1)',
    'grc': 'nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2',
    'gsw': 'nplurals=2; plural=(n != 1)',
    'gu': 'nplurals=2; plural=(n > 1)',
    'gu_IN': 'nplurals=2; plural=(n > 1)',
    'guc': 'nplurals=2; plural=(n != 1)',
    'gug': 'nplurals=2; plural=(n > 1)',
    'gum': 'nplurals=2; plural=(n != 1)',
    'gun': 'nplurals=2; plural=(n > 1)',
    'gur': 'nplurals=2; plural=(n != 1)',
    'guw': 'nplurals=2; plural=(n > 1)',
    'guz': 'nplurals=2; plural=(n != 1)',
    'gv': 'nplurals=4; plural=(n % 10 == 1) ? 0 : ((n % 10 == 2) ? 1 : ((n % 100 == 0 || n % 100 == 20 || n % 100 == 40 || n % 100 == 60 || n % 100 == 80) ? 2 : 3))',
    'gwi': 'nplurals=2; plural=(n != 1)',
    'ha': 'nplurals=2; plural=(n != 1)',
    'hai': 'nplurals=2; plural=(n != 1)',
    'hak_Hans': 'nplurals=1; plural=0',
    'hak_Hant': 'nplurals=1; plural=0',
    'hak_Latn': 'nplurals=1; plural=0',
    'haw': 'nplurals=2; plural=(n != 1)',
    'haz': 'nplurals=2; plural=(n != 1)',
    'he': 'nplurals=4; plural=(n == 1) ? 0 : ((n == 2) ? 1 : ((n > 10 && n % 10 == 0) ? 2 : 3))',
    'he_IL': 'nplurals=4; plural=(n == 1) ? 0 : ((n == 2) ? 1 : ((n > 10 && n % 10 == 0) ? 2 : 3))',
    'hi': 'nplurals=2; plural=(n > 1)',
    'hi@hinglish': 'nplurals=2; plural=(n > 1)',
    'hi_Latn': 'nplurals=2; plural=(n > 1)',
    'hil': 'nplurals=2; plural=(n != 1)',
    'hit': 'nplurals=2; plural=(n != 1)',
    'hmn': 'nplurals=2; plural=(n != 1)',
    'hnd': 'nplurals=2; plural=(n != 1)',
    'hne': 'nplurals=2; plural=(n != 1)',
    'hnj': 'nplurals=1; plural=0',
    'hno': 'nplurals=2; plural=(n != 1)',
    'ho': 'nplurals=2; plural=(n != 1)',
    'hoc': 'nplurals=2; plural=(n != 1)',
    'hoj': 'nplurals=2; plural=(n != 1)',
    'hr': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'hrx': 'nplurals=2; plural=(n != 1)',
    'hsb': 'nplurals=4; plural=(n % 100 == 1) ? 0 : ((n % 100 == 2) ? 1 : ((n % 100 == 3 || n % 100 == 4) ? 2 : 3))',
    'hsn': 'nplurals=1; plural=0',
    'ht': 'nplurals=2; plural=(n != 1)',
    'hu': 'nplurals=2; plural=(n != 1)',
    'hup': 'nplurals=2; plural=(n != 1)',
    'hus': 'nplurals=2; plural=(n != 1)',
    'hy': 'nplurals=2; plural=(n > 1)',
    'hz': 'nplurals=2; plural=(n != 1)',
    'ia': 'nplurals=2; plural=(n != 1)',
    'iba': 'nplurals=2; plural=(n != 1)',
    'ibb': 'nplurals=2; plural=(n != 1)',
    'id': 'nplurals=1; plural=0',
    'ie': 'nplurals=2; plural=(n != 1)',
    'ig': 'nplurals=1; plural=0',
    'ii': 'nplurals=1; plural=0',
    'ik': 'nplurals=2; plural=(n != 1)',
    'ilo': 'nplurals=2; plural=(n != 1)',
    'inh': 'nplurals=2; plural=(n != 1)',
    'io': 'nplurals=2; plural=(n != 1)',
    'is': 'nplurals=2; plural=n % 10 != 1 || n % 100 == 11',
    'it': 'nplurals=2; plural=(n != 1)',
    'it@formal': 'nplurals=2; plural=(n != 1)',
    'it@informal': 'nplurals=2; plural=(n != 1)',
    'it_CH': 'nplurals=2; plural=(n != 1)',
    'iu': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'iu_Latn': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'ja': 'nplurals=1; plural=0',
    'ja_KS': 'nplurals=1; plural=0',
    'jam': 'nplurals=2; plural=(n != 1)',
    'jbo': 'nplurals=1; plural=0',
    'jgo': 'nplurals=2; plural=(n != 1)',
    'jmc': 'nplurals=2; plural=(n != 1)',
    'jpr': 'nplurals=2; plural=(n != 1)',
    'jrb': 'nplurals=2; plural=(n != 1)',
    'jv': 'nplurals=1; plural=0',
    'ka': 'nplurals=2; plural=(n != 1)',
    'kaa': 'nplurals=2; plural=(n != 1)',
    'kab': 'nplurals=2; plural=(n > 1)',
    'kac': 'nplurals=2; plural=(n != 1)',
    'kaj': 'nplurals=2; plural=(n != 1)',
    'kam': 'nplurals=2; plural=(n != 1)',
    'kaw': 'nplurals=2; plural=(n != 1)',
    'kbd': 'nplurals=2; plural=(n != 1)',
    'kcg': 'nplurals=2; plural=(n != 1)',
    'kde': 'nplurals=1; plural=0',
    'kea': 'nplurals=1; plural=0',
    'kfr': 'nplurals=2; plural=(n != 1)',
    'kfy': 'nplurals=2; plural=(n != 1)',
    'kg': 'nplurals=2; plural=(n != 1)',
    'kha': 'nplurals=2; plural=(n != 1)',
    'khn': 'nplurals=2; plural=(n != 1)',
    'kho': 'nplurals=2; plural=(n != 1)',
    'ki': 'nplurals=2; plural=(n != 1)',
    'kj': 'nplurals=2; plural=(n != 1)',
    'kk': 'nplurals=2; plural=(n != 1)',
    'kk_Latn': 'nplurals=2; plural=(n != 1)',
    'kkj': 'nplurals=2; plural=(n != 1)',
    'kl': 'nplurals=2; plural=(n != 1)',
    'kln': 'nplurals=2; plural=(n != 1)',
    'km': 'nplurals=1; plural=0',
    'kmb': 'nplurals=2; plural=(n != 1)',
    'kmr': 'nplurals=2; plural=(n != 1)',
    'kmr_Latn': 'nplurals=2; plural=(n != 1)',
    'kn': 'nplurals=2; plural=(n > 1)',
    'ko': 'nplurals=1; plural=0',
    'kok': 'nplurals=2; plural=(n != 1)',
    'kos': 'nplurals=1; plural=0',
    'kpe': 'nplurals=2; plural=(n != 1)',
    'kr': 'nplurals=2; plural=(n != 1)',
    'krc': 'nplurals=2; plural=(n != 1)',
    'kri': 'nplurals=2; plural=(n != 1)',
    'krl': 'nplurals=2; plural=(n != 1)',
    'kru': 'nplurals=2; plural=(n != 1)',
    'ks': 'nplurals=2; plural=(n != 1)',
    'ksb': 'nplurals=2; plural=(n != 1)',
    'ksh': 'nplurals=3; plural=n==0 ? 0 : n==1 ? 1 : 2',
    'ku': 'nplurals=2; plural=(n != 1)',
    'kum': 'nplurals=2; plural=(n != 1)',
    'kut': 'nplurals=2; plural=(n != 1)',
    'kv': 'nplurals=2; plural=(n != 1)',
    'kw': 'nplurals=6; plural=(n == 0) ? 0 : ((n == 1) ? 1 : (((n % 100 == 2 || n % 100 == 22 || n % 100 == 42 || n % 100 == 62 || n % 100 == 82) || n % 1000 == 0 && (n % 100000 >= 1000 && n % 100000 <= 20000 || n % 100000 == 40000 || n % 100000 == 60000 || n % 100000 == 80000) || n != 0 && n % 1000000 == 100000) ? 2 : ((n % 100 == 3 || n % 100 == 23 || n % 100 == 43 || n % 100 == 63 || n % 100 == 83) ? 3 : ((n != 1 && (n % 100 == 1 || n % 100 == 21 || n % 100 == 41 || n % 100 == 61 || n % 100 == 81)) ? 4 : 5))))',
    'kxm': 'nplurals=2; plural=(n != 1)',
    'ky': 'nplurals=2; plural=(n != 1)',
    'la': 'nplurals=2; plural=(n != 1)',
    'lad': 'nplurals=2; plural=(n != 1)',
    'lag': 'nplurals=3; plural=(n == 0) ? 0 : ((n == 1) ? 1 : 2)',
    'laj': 'nplurals=2; plural=(n != 1)',
    'lam': 'nplurals=2; plural=(n != 1)',
    'lb': 'nplurals=2; plural=(n != 1)',
    'lez': 'nplurals=2; plural=(n != 1)',
    'lfn': 'nplurals=2; plural=(n != 1)',
    'lg': 'nplurals=2; plural=(n != 1)',
    'li': 'nplurals=2; plural=(n != 1)',
    'lij': 'nplurals=2; plural=(n != 1)',
    'ljp': 'nplurals=2; plural=(n != 1)',
    'lki': 'nplurals=2; plural=(n != 1)',
    'lkt': 'nplurals=1; plural=0',
    'lld': 'nplurals=3; plural=(n == 1) ? 0 : ((n != 0 && n % 1000000 == 0) ? 1 : 2)',
    'lmn': 'nplurals=2; plural=(n != 1)',
    'lmo': 'nplurals=2; plural=(n != 1)',
    'ln': 'nplurals=2; plural=(n > 1)',
    'lo': 'nplurals=1; plural=0',
    'lol': 'nplurals=2; plural=(n != 1)',
    'loz': 'nplurals=2; plural=(n != 1)',
    'lrc': 'nplurals=2; plural=(n != 1)',
    'lt': 'nplurals=3; plural=(n % 10 == 1 && (n % 100 < 11 || n % 100 > 19)) ? 0 : ((n % 10 >= 2 && n % 10 <= 9 && (n % 100 < 11 || n % 100 > 19)) ? 1 : 2)',
    'ltg': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2',
    'lu': 'nplurals=2; plural=(n != 1)',
    'lua': 'nplurals=2; plural=(n != 1)',
    'lui': 'nplurals=2; plural=(n != 1)',
    'lun': 'nplurals=2; plural=(n != 1)',
    'luo': 'nplurals=2; plural=(n != 1)',
    'lus': 'nplurals=2; plural=(n != 1)',
    'luy': 'nplurals=2; plural=(n != 1)',
    'luz': 'nplurals=2; plural=(n != 1)',
    'lv': 'nplurals=3; plural=(n % 10 == 0 || n % 100 >= 11 && n % 100 <= 19) ? 0 : ((n % 10 == 1 && n % 100 != 11) ? 1 : 2)',
    'lv@formal': 'nplurals=3; plural=(n % 10 == 0 || n % 100 >= 11 && n % 100 <= 19) ? 0 : ((n % 10 == 1 && n % 100 != 11) ? 1 : 2)',
    'lv@informal': 'nplurals=3; plural=(n % 10 == 0 || n % 100 >= 11 && n % 100 <= 19) ? 0 : ((n % 10 == 1 && n % 100 != 11) ? 1 : 2)',
    'lzh': 'nplurals=1; plural=0',
    'mad': 'nplurals=2; plural=(n != 1)',
    'mag': 'nplurals=2; plural=(n != 1)',
    'mai': 'nplurals=2; plural=(n != 1)',
    'mak': 'nplurals=2; plural=(n != 1)',
    'man': 'nplurals=2; plural=(n != 1)',
    'mas': 'nplurals=2; plural=(n != 1)',
    'mdf': 'nplurals=2; plural=(n != 1)',
    'mdh': 'nplurals=2; plural=(n != 1)',
    'mdr': 'nplurals=2; plural=(n != 1)',
    'men': 'nplurals=2; plural=(n != 1)',
    'mer': 'nplurals=2; plural=(n != 1)',
    'mfa': 'nplurals=2; plural=(n != 1)',
    'mfe': 'nplurals=2; plural=(n > 1)',
    'mg': 'nplurals=2; plural=(n > 1)',
    'mga': 'nplurals=2; plural=(n != 1)',
    'mgh': 'nplurals=2; plural=(n != 1)',
    'mgo': 'nplurals=2; plural=(n != 1)',
    'mh': 'nplurals=2; plural=(n != 1)',
    'mhr': 'nplurals=2; plural=(n != 1)',
    'mi': 'nplurals=2; plural=(n > 1)',
    'mia': 'nplurals=2; plural=(n > 1)',
    'mic': 'nplurals=2; plural=(n != 1)',
    'min': 'nplurals=2; plural=(n != 1)',
    'mjw': 'nplurals=2; plural=(n != 1)',
    'mk': 'nplurals=2; plural=n==1 || n%10==1 ? 0 : 1',
    'ml': 'nplurals=2; plural=(n != 1)',
    'mn': 'nplurals=2; plural=(n != 1)',
    'mn_Cyrl': 'nplurals=2; plural=(n != 1)',
    'mn_Mong': 'nplurals=2; plural=(n != 1)',
    'mnc': 'nplurals=2; plural=(n != 1)',
    'mni': 'nplurals=2; plural=(n != 1)',
    'mnk': 'nplurals=3; plural=n==0 ? 0 : n==1 ? 1 : 2',
    'mnw': 'nplurals=2; plural=(n != 1)',
    'moe': 'nplurals=2; plural=(n != 1)',
    'moh': 'nplurals=2; plural=(n != 1)',
    'mos': 'nplurals=2; plural=(n != 1)',
    'mr': 'nplurals=2; plural=(n != 1)',
    'mrh': 'nplurals=2; plural=(n != 1)',
    'ms': 'nplurals=1; plural=0',
    'ms_Arab': 'nplurals=1; plural=0',
    'mt': 'nplurals=4; plural=n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3',
    'mtr': 'nplurals=2; plural=(n != 1)',
    'mus': 'nplurals=2; plural=(n != 1)',
    'mwk': 'nplurals=2; plural=(n != 1)',
    'mwl': 'nplurals=2; plural=(n != 1)',
    'mwr': 'nplurals=2; plural=(n != 1)',
    'mww': 'nplurals=2; plural=(n != 1)',
    'mxc': 'nplurals=2; plural=(n != 1)',
    'my': 'nplurals=1; plural=0',
    'my@Zawgyi': 'nplurals=1; plural=0',
    'myv': 'nplurals=2; plural=(n != 1)',
    'myx': 'nplurals=2; plural=(n != 1)',
    'mzn': 'nplurals=2; plural=(n != 1)',
    'na': 'nplurals=2; plural=(n != 1)',
    'nah': 'nplurals=2; plural=(n != 1)',
    'nan_Hans': 'nplurals=1; plural=0',
    'nan_Hant': 'nplurals=1; plural=0',
    'nan_Hntl_pehoeji': 'nplurals=1; plural=0',
    'nan_Hntl_tailo': 'nplurals=1; plural=0',
    'nan_Latn_pehoeji': 'nplurals=1; plural=0',
    'nan_Latn_tailo': 'nplurals=1; plural=0',
    'nan_Qabs_pehoeji': 'nplurals=1; plural=0',
    'nan_Qabs_tailo': 'nplurals=1; plural=0',
    'nap': 'nplurals=2; plural=(n != 1)',
    'naq': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'nb_NO': 'nplurals=2; plural=(n != 1)',
    'nd': 'nplurals=2; plural=(n != 1)',
    'ndc': 'nplurals=2; plural=(n != 1)',
    'nds': 'nplurals=2; plural=(n != 1)',
    'ne': 'nplurals=2; plural=(n != 1)',
    'new': 'nplurals=2; plural=(n != 1)',
    'ng': 'nplurals=2; plural=(n != 1)',
    'ngl': 'nplurals=2; plural=(n != 1)',
    'nia': 'nplurals=2; plural=(n != 1)',
    'nij': 'nplurals=2; plural=(n != 1)',
    'niu': 'nplurals=2; plural=(n != 1)',
    'nl': 'nplurals=2; plural=(n != 1)',
    'nl@formal': 'nplurals=2; plural=(n != 1)',
    'nl@informal': 'nplurals=2; plural=(n != 1)',
    'nl_BE': 'nplurals=2; plural=(n != 1)',
    'nn': 'nplurals=2; plural=(n != 1)',
    'nnh': 'nplurals=2; plural=(n != 1)',
    'nod': 'nplurals=2; plural=(n != 1)',
    'noe': 'nplurals=2; plural=(n != 1)',
    'nog': 'nplurals=2; plural=(n != 1)',
    'non': 'nplurals=2; plural=(n != 1)',
    'nqo': 'nplurals=1; plural=0',
    'nr': 'nplurals=2; plural=(n != 1)',
    'nso': 'nplurals=2; plural=(n > 1)',
    'nuk': 'nplurals=2; plural=(n != 1)',
    'nv': 'nplurals=2; plural=(n != 1)',
    'nwc': 'nplurals=2; plural=(n != 1)',
    'ny': 'nplurals=2; plural=(n != 1)',
    'nym': 'nplurals=2; plural=(n != 1)',
    'nyn': 'nplurals=2; plural=(n != 1)',
    'nyo': 'nplurals=2; plural=(n != 1)',
    'nzi': 'nplurals=2; plural=(n != 1)',
    'oc': 'nplurals=2; plural=(n > 1)',
    'oj': 'nplurals=2; plural=(n != 1)',
    'om': 'nplurals=2; plural=(n != 1)',
    'or': 'nplurals=2; plural=(n != 1)',
    'os': 'nplurals=2; plural=(n != 1)',
    'osa': 'nplurals=1; plural=0',
    'ota': 'nplurals=2; plural=(n != 1)',
    'otk': 'nplurals=2; plural=(n != 1)',
    'otq': 'nplurals=2; plural=(n != 1)',
    'ovd': 'nplurals=2; plural=(n != 1)',
    'pa': 'nplurals=2; plural=(n > 1)',
    'pa_PK': 'nplurals=2; plural=(n > 1)',
    'pag': 'nplurals=2; plural=(n != 1)',
    'pal': 'nplurals=2; plural=(n != 1)',
    'pam': 'nplurals=2; plural=(n != 1)',
    'pap': 'nplurals=2; plural=(n != 1)',
    'pau': 'nplurals=2; plural=(n != 1)',
    'pbb': 'nplurals=2; plural=(n != 1)',
    'pcm': 'nplurals=2; plural=(n > 1)',
    'pdt': 'nplurals=2; plural=(n != 1)',
    'peo': 'nplurals=2; plural=(n != 1)',
    'phn': 'nplurals=2; plural=(n != 1)',
    'pi': 'nplurals=2; plural=(n != 1)',
    'pl': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'pl@formal': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'pl@informal': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'pms': 'nplurals=2; plural=(n != 1)',
    'pon': 'nplurals=2; plural=(n != 1)',
    'prg': 'nplurals=3; plural=(n % 10 == 0 || n % 100 >= 11 && n % 100 <= 19) ? 0 : ((n % 10 == 1 && n % 100 != 11) ? 1 : 2)',
    'pro': 'nplurals=2; plural=(n != 1)',
    'prs': 'nplurals=2; plural=(n != 1)',
    'ps': 'nplurals=2; plural=(n != 1)',
    'pt': 'nplurals=2; plural=(n > 1)',
    'pt@formal': 'nplurals=2; plural=(n > 1)',
    'pt@informal': 'nplurals=2; plural=(n > 1)',
    'pt_AO': 'nplurals=2; plural=(n > 1)',
    'pt_BR': 'nplurals=2; plural=(n > 1)',
    'pt_BR@formal': 'nplurals=2; plural=(n > 1)',
    'pt_BR@informal': 'nplurals=2; plural=(n > 1)',
    'pt_PT': 'nplurals=2; plural=(n > 1)',
    'pwn': 'nplurals=2; plural=(n != 1)',
    'qdt': 'nplurals=2; plural=(n > 1)',
    'qpv': 'nplurals=1; plural=0',
    'qtp': 'nplurals=2; plural=(n > 1)',
    'qu': 'nplurals=2; plural=(n != 1)',
    'qu_EC': 'nplurals=2; plural=(n != 1)',
    'quc': 'nplurals=2; plural=(n != 1)',
    'qug': 'nplurals=2; plural=(n != 1)',
    'qya': 'nplurals=2; plural=(n != 1)',
    'raj': 'nplurals=2; plural=(n != 1)',
    'rap': 'nplurals=2; plural=(n != 1)',
    'rar': 'nplurals=2; plural=(n != 1)',
    'rcf': 'nplurals=2; plural=(n != 1)',
    'rej': 'nplurals=2; plural=(n != 1)',
    'rhg': 'nplurals=2; plural=(n != 1)',
    'rif': 'nplurals=2; plural=(n != 1)',
    'rkt': 'nplurals=2; plural=(n != 1)',
    'rm': 'nplurals=2; plural=(n != 1)',
    'rmt': 'nplurals=2; plural=(n != 1)',
    'rn': 'nplurals=2; plural=(n != 1)',
    'rng': 'nplurals=2; plural=(n != 1)',
    'ro': 'nplurals=3; plural=n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2',
    'ro_MD': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 0 || n % 100 >= 2 && n % 100 <= 19) ? 1 : 2)',
    'rof': 'nplurals=2; plural=(n != 1)',
    'rom': 'nplurals=2; plural=(n != 1)',
    'ru': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'ru@formal': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'ru@informal': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'ru_UA': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'rue': 'nplurals=2; plural=(n != 1)',
    'rup': 'nplurals=2; plural=(n != 1)',
    'rw': 'nplurals=2; plural=(n != 1)',
    'rwk': 'nplurals=2; plural=(n != 1)',
    'sa': 'nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2',
    'sad': 'nplurals=2; plural=(n != 1)',
    'sah': 'nplurals=1; plural=0',
    'sai': 'nplurals=2; plural=(n != 1)',
    'sam': 'nplurals=2; plural=(n != 1)',
    'saq': 'nplurals=2; plural=(n != 1)',
    'sas': 'nplurals=2; plural=(n != 1)',
    'sat': 'nplurals=3; plural=n == 1 ? 0 : n == 2 ? 1 : 2',
    'sc': 'nplurals=2; plural=(n != 1)',
    'sck': 'nplurals=2; plural=(n != 1)',
    'scn': 'nplurals=3; plural=(n == 1) ? 0 : ((n != 0 && n % 1000000 == 0) ? 1 : 2)',
    'sco': 'nplurals=2; plural=(n != 1)',
    'sd': 'nplurals=2; plural=(n != 1)',
    'sdh': 'nplurals=2; plural=(n != 1)',
    'se': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'sef': 'nplurals=2; plural=(n != 1)',
    'seh': 'nplurals=2; plural=(n != 1)',
    'sel': 'nplurals=2; plural=(n != 1)',
    'ses': 'nplurals=1; plural=0',
    'sg': 'nplurals=1; plural=0',
    'sga': 'nplurals=2; plural=(n != 1)',
    'sgn': 'nplurals=2; plural=(n != 1)',
    'sgs': 'nplurals=2; plural=(n != 1)',
    'shi': 'nplurals=3; plural=(n == 0 || n == 1) ? 0 : ((n >= 2 && n <= 10) ? 1 : 2)',
    'shn': 'nplurals=2; plural=(n != 1)',
    'si': 'nplurals=2; plural=(n > 1)',
    'sid': 'nplurals=2; plural=(n != 1)',
    'sjd': 'nplurals=2; plural=(n != 1)',
    'sk': 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2',
    'skr': 'nplurals=2; plural=(n != 1)',
    'sl': 'nplurals=4; plural=n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3',
    'sm': 'nplurals=2; plural=(n != 1)',
    'sma': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'smi': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'smj': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'sml': 'nplurals=2; plural=(n != 1)',
    'smn': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'sms': 'nplurals=3; plural=(n == 1) ? 0 : ((n == 2) ? 1 : 2)',
    'sn': 'nplurals=2; plural=(n != 1)',
    'snk': 'nplurals=2; plural=(n != 1)',
    'so': 'nplurals=2; plural=(n != 1)',
    'sog': 'nplurals=2; plural=(n != 1)',
    'son': 'nplurals=1; plural=0',
    'sou': 'nplurals=2; plural=(n != 1)',
    'sq': 'nplurals=2; plural=(n != 1)',
    'sr': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'sr@ijekavian': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'sr@ijekavian_Latn': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'sr_Cyrl': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'sr_Latn': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'srn': 'nplurals=2; plural=(n != 1)',
    'srr': 'nplurals=2; plural=(n != 1)',
    'ss': 'nplurals=2; plural=(n != 1)',
    'ssy': 'nplurals=2; plural=(n != 1)',
    'st': 'nplurals=2; plural=(n != 1)',
    'su': 'nplurals=1; plural=0',
    'suk': 'nplurals=2; plural=(n != 1)',
    'sus': 'nplurals=2; plural=(n != 1)',
    'sux': 'nplurals=2; plural=(n != 1)',
    'sv': 'nplurals=2; plural=(n != 1)',
    'sw': 'nplurals=2; plural=(n != 1)',
    'sw_CD': 'nplurals=2; plural=(n != 1)',
    'sw_TZ': 'nplurals=2; plural=(n != 1)',
    'swb': 'nplurals=2; plural=(n != 1)',
    'swg': 'nplurals=2; plural=(n != 1)',
    'swv': 'nplurals=2; plural=(n != 1)',
    'sxu': 'nplurals=2; plural=(n != 1)',
    'syc': 'nplurals=2; plural=(n != 1)',
    'syl': 'nplurals=2; plural=(n != 1)',
    'syr': 'nplurals=2; plural=(n != 1)',
    'szl': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'szy': 'nplurals=2; plural=(n != 1)',
    'ta': 'nplurals=2; plural=(n != 1)',
    'ta_LK': 'nplurals=2; plural=(n != 1)',
    'tay': 'nplurals=2; plural=(n != 1)',
    'tcy': 'nplurals=2; plural=(n != 1)',
    'te': 'nplurals=2; plural=(n != 1)',
    'tem': 'nplurals=2; plural=(n != 1)',
    'teo': 'nplurals=2; plural=(n != 1)',
    'ter': 'nplurals=2; plural=(n != 1)',
    'tet': 'nplurals=2; plural=(n != 1)',
    'tg': 'nplurals=2; plural=(n > 1)',
    'th': 'nplurals=1; plural=0',
    'ti': 'nplurals=2; plural=(n > 1)',
    'tig': 'nplurals=2; plural=(n != 1)',
    'tiv': 'nplurals=2; plural=(n != 1)',
    'tk': 'nplurals=2; plural=(n != 1)',
    'tkl': 'nplurals=2; plural=(n != 1)',
    'tl': 'nplurals=2; plural=n != 1 && n != 2 && n != 3 && (n % 10 == 4 || n % 10 == 6 || n % 10 == 9)',
    'tlh': 'nplurals=1; plural=0',
    'tlh_Piqd': 'nplurals=1; plural=0',
    'tli': 'nplurals=2; plural=(n != 1)',
    'tly': 'nplurals=2; plural=(n != 1)',
    'tmh': 'nplurals=2; plural=(n != 1)',
    'tn': 'nplurals=2; plural=(n != 1)',
    'to': 'nplurals=1; plural=0',
    'tog': 'nplurals=2; plural=(n != 1)',
    'toi': 'nplurals=2; plural=(n != 1)',
    'tok': 'nplurals=1; plural=0',
    'tpi': 'nplurals=1; plural=0',
    'tr': 'nplurals=2; plural=(n != 1)',
    'trv': 'nplurals=2; plural=(n != 1)',
    'ts': 'nplurals=2; plural=(n != 1)',
    'tsg': 'nplurals=2; plural=(n != 1)',
    'tsi': 'nplurals=2; plural=(n != 1)',
    'tsj': 'nplurals=2; plural=(n != 1)',
    'tt': 'nplurals=1; plural=0',
    'tt@iqtelif': 'nplurals=1; plural=0',
    'tts': 'nplurals=2; plural=(n != 1)',
    'tum': 'nplurals=2; plural=(n != 1)',
    'tvl': 'nplurals=2; plural=(n != 1)',
    'tw': 'nplurals=2; plural=(n != 1)',
    'ty': 'nplurals=2; plural=(n != 1)',
    'tyv': 'nplurals=2; plural=(n != 1)',
    'tzj': 'nplurals=2; plural=(n != 1)',
    'tzl': 'nplurals=2; plural=(n != 1)',
    'tzm': 'nplurals=2; plural=n >= 2 && (n < 11 || n > 99)',
    'udm': 'nplurals=2; plural=(n != 1)',
    'ug': 'nplurals=2; plural=(n != 1)',
    'uga': 'nplurals=2; plural=(n != 1)',
    'uk': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'umb': 'nplurals=2; plural=(n != 1)',
    'und': 'nplurals=2; plural=(n != 1)',
    'unr': 'nplurals=2; plural=(n != 1)',
    'ur': 'nplurals=2; plural=(n != 1)',
    'ur_IN': 'nplurals=2; plural=(n != 1)',
    'ur_PK': 'nplurals=2; plural=(n != 1)',
    'uz': 'nplurals=2; plural=(n != 1)',
    'uz_Latn': 'nplurals=2; plural=(n != 1)',
    'vai': 'nplurals=2; plural=(n != 1)',
    've': 'nplurals=2; plural=(n != 1)',
    'vec': 'nplurals=3; plural=(n == 1) ? 0 : ((n != 0 && n % 1000000 == 0) ? 1 : 2)',
    'vi': 'nplurals=1; plural=0',
    'vls': 'nplurals=2; plural=(n != 1)',
    'vmf': 'nplurals=2; plural=(n != 1)',
    'vmw': 'nplurals=2; plural=(n != 1)',
    'vo': 'nplurals=2; plural=(n != 1)',
    'vot': 'nplurals=2; plural=(n != 1)',
    'vro': 'nplurals=2; plural=(n != 1)',
    'vun': 'nplurals=2; plural=(n != 1)',
    'wa': 'nplurals=2; plural=(n > 1)',
    'wae': 'nplurals=2; plural=(n != 1)',
    'wal': 'nplurals=2; plural=(n != 1)',
    'war': 'nplurals=2; plural=(n != 1)',
    'was': 'nplurals=2; plural=(n != 1)',
    'wbq': 'nplurals=2; plural=(n != 1)',
    'wbr': 'nplurals=2; plural=(n != 1)',
    'wen': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2',
    'wep': 'nplurals=2; plural=(n != 1)',
    'wo': 'nplurals=1; plural=0',
    'wtm': 'nplurals=2; plural=(n != 1)',
    'wuu_Hans': 'nplurals=1; plural=0',
    'wuu_Hant': 'nplurals=1; plural=0',
    'xal': 'nplurals=2; plural=(n != 1)',
    'xh': 'nplurals=2; plural=(n != 1)',
    'xnr': 'nplurals=2; plural=(n != 1)',
    'xog': 'nplurals=2; plural=(n != 1)',
    'yao': 'nplurals=2; plural=(n != 1)',
    'yap': 'nplurals=2; plural=(n != 1)',
    'yi': 'nplurals=2; plural=(n != 1)',
    'yo': 'nplurals=1; plural=0',
    'yua': 'nplurals=2; plural=(n != 1)',
    'yue_Hans': 'nplurals=1; plural=0',
    'yue_Hant': 'nplurals=1; plural=0',
    'za': 'nplurals=2; plural=(n != 1)',
    'zap': 'nplurals=2; plural=(n != 1)',
    'zbl': 'nplurals=2; plural=(n != 1)',
    'zen': 'nplurals=2; plural=(n != 1)',
    'zgh': 'nplurals=2; plural=(n != 1)',
    'zh_Hans': 'nplurals=1; plural=0',
    'zh_Hans_SG': 'nplurals=1; plural=0',
    'zh_Hant': 'nplurals=1; plural=0',
    'zh_Hant_HK': 'nplurals=1; plural=0',
    'zh_Latn': 'nplurals=1; plural=0',
    'zu': 'nplurals=2; plural=(n > 1)',
    'zun': 'nplurals=2; plural=(n != 1)',
    'zza': 'nplurals=2; plural=(n != 1)',
}
